config/routes.rb
    Rails.application.routes.draw do

  devise_for :users
    
  resources :users do
    resources :favorites
  end

  root :to => redirect('/videos/viewCount')

  get 'videos/:order(/:page_token)/results' => 'videos#results'
  
  get 'videos/:order(/:page_token)' => 'videos#search'

  get '*path' => redirect('/')

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	belongs_to :user, inverse_of: :favorites
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :favorites, :dependent => :destroy, inverse_of: :user
end

app/models/yt_search.rb
class YtSearch
  def initialize(order = "viewCount", page_token = "")
    @response = HTTParty.get("https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=15&order=#{order}&pageToken=#{page_token}&q=cats%7Clolcat%7Cfunnycats&type=video&videoEmbeddable=true&key=#{ENV["YT_API_KEY"]}")
    @next_page = @response["nextPageToken"] 
    @prev_page = @response["prevPageToken"]
  end

  attr_reader :response, :next_page, :prev_page

  def [](key)
    self.response["items"][key]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def index
		@favorites = current_user.favorites
	end

	def create
		user = current_user
		favorite = user.favorites.new(favorite_params)
		favorite.save
		render nothing: true
	end

	private

		def favorite_params
			params.require(:favorite).permit(:yt_id, :title, :thumbnail)
		end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

	def search
	end

	def results
		@result = YtSearch.new(params[:order], params[:page_token])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/favorites/index.haml
%ul
	- @favorites.each do |video|
		%li
			%h3= video.title

app/views/layouts/application.html.haml
!!! 5
%html{'ng-app' => 'lolCat'}
	%head
	%base{:href => '/'}
	%title LolCat
	= stylesheet_link_tag    'application', media: 'all'
	= javascript_include_tag 'application'
	= csrf_meta_tags
	%body
		= render "shared/header"
		= render "shared/searching"
		= yield
		%div{'ng-view' =>''}

app/views/layouts/devise.haml
!!! 5
%html{'ng-app' => 'lolCat'}
	%head
	%base{:href => '/'}
	%title LolCat
	= stylesheet_link_tag    'application', media: 'all'
	= javascript_include_tag 'application'
	= csrf_meta_tags
	%body#devise_body
		= render "shared/header"
		.container-fluid
			.row
				.col-md-4.col-md-offset-4#registration_bloc
					= yield

app/views/layouts/favorites.html.haml
!!! 5
%html{'ng-app' => 'lolCat'}
	%head
	%base{:href => '/'}
	%title LolCat
	= stylesheet_link_tag    'application', media: 'all'
	= javascript_include_tag 'application'
	= csrf_meta_tags
	%body
		= render "shared/header"
		.container-fluid
			.row
			= yield

app/views/layouts/videos.html.haml
!!! 5
%html{'ng-app' => 'lolCat'}
	%head
	%base{:href => '/'}
	%title LolCat
	= stylesheet_link_tag    'application', media: 'all'
	= javascript_include_tag 'application'
	= csrf_meta_tags
	%body
		%div{:id => "div-user-data", "data-user-id" => "#{user_signed_in? ? current_user.id: nil}" }
		= render "shared/header"
		.container-fluid
			.row
			= yield
			%div{'ng-view' =>''}

app/views/shared/_header.html.haml
%nav.navbar.navbar-default#header
	.container-fluid
		= image_tag("logo.png", :class => "img-responsive navbar-nav", :id => "logo")
		= render 'shared/searching'			
		.collapse.navbar-collapse
			.nav.navbar-nav.navbar-right
				- if user_signed_in?
					%span= current_user.email
					= render 'shared/menu'
				- else
					= render 'shared/sign_in'
					= render 'shared/sign_up'

app/views/shared/_menu.html.haml
.btn-group.navbar-btn
  %button.btn.btn-default{:type => "button"} Menu
  %button.btn.btn-default.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
    %span.caret
    %span.sr-only Toggle Dropdown
  %ul.dropdown-menu
    %li
      = link_to edit_user_registration_path, method: :get do
        %span{:class => "glyphicon glyphicon-pencil", "aria-hidden" => "true"}
        %span Edit profil
    %li
      = link_to user_favorites_path(current_user.id), method: :get do
        %span{:class => "glyphicon glyphicon-folder-open", "aria-hidden" => "true"}
        %span Favorite
    %li.divider{:role => "separator"}
    %li
      = link_to destroy_user_session_path, method: :delete do
        %span{:class => "glyphicon glyphicon-off", "aria-hidden" => "true"}
        %span Log Out

app/views/shared/_searching.html.haml
%ul.nav.navbar-nav#searching_buttons
	%li.active#most_popular
		= link_to "Most Popular", "videos/viewCount"
	%li#most_recent
		= link_to "Most Recent", "videos/date"

app/views/shared/_sign_in.html.haml
%button{:type => "button", :class => "btn btn-default navbar-btn", "data-toggle" => "modal", "data-target" => "#sign_in_modal"}Sign In

%div{:class => "modal fade", :id => "sign_in_modal", :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel"}
  %div{:class => "modal-dialog", :role => "document"}
    .modal-content
      .modal-header
        %button{:type => "button", :class => "close", "data-dismiss" => "modal", "aria-label" => "Close"}
          %span{"aria-hidden" => "true"} &times;
        %h4{:class => "modal-title", :id => "myModalLabel"}Sign In
      
      = form_for(:user, url: session_path(:user)) do |f|
        .modal-body
          .field.form-group
            = f.label :email
            %br
            = f.email_field :email, autofocus: true, class: "form-control"
          .field.form-group
            = f.label :password
            %br
            = f.password_field :password, autocomplete: "off", class: "form-control"
          - if devise_mapping.rememberable?
            .field
              = f.check_box :remember_me
              = f.label :remember_me

        .modal-footer.actions
          = f.submit "Sign in" ,class: "btn btn-primary"

app/views/shared/_sign_out.html.haml
= link_to "Déconnexion", destroy_user_session_path, method: :delete, :class => "btn btn-primary navbar-btn"

app/views/shared/_sign_up.html.haml
%button{:type => "button", :class => "btn btn-primary navbar-btn", "data-toggle" => "modal", "data-target" => "#sign_up_modal"}Sign Up

%div{:class => "modal fade", :id => "sign_up_modal", :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel"}
  %div{:class => "modal-dialog", :role => "document"}
    .modal-content
      .modal-header
        %button{:type => "button", :class => "close", "data-dismiss" => "modal", "aria-label" => "Close"}
          %span{"aria-hidden" => "true"} &times;
        %h4{:class => "modal-title", :id => "myModalLabel"}Sign Up
      
      = form_for(:user, url: registration_path(:user)) do |f|
        .modal-body
          .field.form-group
            = f.label :email
            %br
            = f.email_field :email, autofocus: true, class: "form-control"
          .field.form-group
            = f.label :password
            - if @minimum_password_length
              %em = (@minimum_password_length + " characters minimum")
            %br
            = f.password_field :password, autocomplete: "off", class: "form-control"
          .field.form-group
            = f.label :password_confirmation
            %br
            = f.password_field :password_confirmation, autocomplete: "off", class: "form-control"

        .modal-footer.actions
          = f.submit "Sign up" ,class: "btn btn-primary"